- name: Install kitty
  shell: curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
  tags: 
    - kitty 
- name: CD root 
  shell: cd ~ 
  tags: 
    - kitty
- name: Create symlinks to add kitty and kitten to PATH 
  shell: ln -sf ~/.local/kitty.app/bin/kitty ~/.local/kitty.app/bin/kitten ~/.local/bin/ 
  tags: 
    - kitty 
- name: Place the kitty.desktop file somewhere it can be found by the OS 
  shell: cp ~/.local/kitty.app/share/applications/kitty.desktop ~/.local/share/applications/
  tags: 
    - kitty
- name: Update paths to kitty and its icon 
  shell: sed -i "s|Icon=kitty|Icon=/home/$USER/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png|g" ~/.local/share/applications/kitty*.desktop && sed -i "s|Exec=kitty|Exec=/home/$USER/.local/kitty.app/bin/kitty|g" ~/.local/share/applications/kitty*.desktop 
  tags: 
    - kitty
